###############################################################################
#
# Functions to format dataframes into Latex
#
###############################################################################

# REMARK: Generated the DOucmentation with AI


#' Clean Strings for LaTeX
#' @description Fixes truncated p-values (e.g., "(0)" -> "(0.00)", "(1)" -> "(1.00)") 
#' to ensure proper alignment in academic tables.
#' 
#' @param x A character string of numbers or float.
#' 
#' @return The cleaned string 
#' 
clean_stat_string <- function(x) {
  x <- as.character(x)
  # Fix zero p-values: "(0)" or "(.0)" -> "(0.00)"
  x <- gsub("\\((0|\\.0+)\\)", "(0.00)", x)
  # Fix integer p-values: "(1)" or "(1.0)" -> "(1.00)"
  x <- gsub("\\((1|1\\.0+)\\)", "(1.00)", x)
  return(x)
}




#' Export Out-of-Sample Forecast Evaluation Summary to LaTeX
#'
#' Converts forecast evaluation metrics generated by \code{creaFcstEval} into a publication-ready
#' LaTeX table containing relative loss ratios (MSFE, MAFE), Diebold-Mariano test statistics,
#' Mincer-Zarnowitz rationality tests, and efficiency diagnostic properties with an academic footnote.
#'
#' @param eval_df A data frame containing evaluation metrics output from \code{creaFcstEval},
#'   including metadata columns (\code{Model}, \code{Benchmark}, \code{Estimation_start},
#'   \code{Evaluation_period}, \code{Estimation_scheme}) and test statistics across horizons (\code{Horizon}).
#' @param output_path Optional character string specifying the file path where the \code{.tex} table
#'   should be saved. If \code{NULL} (default), prints the LaTeX code to the console via \code{cat}.
#'
#' @return Invisibly returns the complete LaTeX table string block.
#'
#' @export
export_eval_to_latex <- function(eval_df, output_path = NULL) {
  #Extract metadata from the data frame
  # (these are repeated and are the same over all lines)
  # AUto ARma causes latex formatting to trigger with Snake case
  model_name  <- as.character(eval_df$Model[1])
  benchmark  <- ifelse(as.character(eval_df$Benchmark[1]) == "AUTO_ARMA", "Auto ARMA", as.character(eval_df$Benchmark[1]))
  est_start   <- as.character(eval_df$Estimation_start[1])
  eval_period <- as.character(eval_df$Evaluation_period[1])
  scheme      <- as.character(eval_df$Estimation_scheme[1])
  
  # Construct the LaTeX code block
  latex_lines <- c(
    "\\begin{table}[htbp]",
    "\\centering",
    sprintf("\\caption{Out-of-Sample Predictive Evaluation: %s vs. %s Benchmark}", model_name, benchmark),
    sprintf("\\label{tab:%s_evaluation}", lclog <- gsub(" ", "_", tolower(model_name))),
    "\\footnotesize",
    "\\begin{tabular}{l cccccccc}",
    "\\hline\\hline",
    "\\rule{0pt}{3ex}",
    "\\textbf{H} & \\textbf{MSFE} & \\textbf{DM MSFE} & \\textbf{MAFE} & \\textbf{DM MAFE} & \\textbf{MZ Test} & \\textbf{Unbias} & \\textbf{Strong Eff} & \\textbf{Weak Eff} \\\\[0.5ex]",
    "\\hline",
    "\\rule{0pt}{2.5ex}"
  )
  
  # Loop through the rows and format the values
  for(i in 1:nrow(eval_df)) {
    horizon   <- eval_df$Horizon[i]
    msfe_rat  <- sprintf("%.2f", as.numeric(eval_df$MSFE_ratio[i]))
    mafe_rat  <- sprintf("%.2f", as.numeric(eval_df$MAFE_ratio[i]))
    
    # clean strings with helper
    dm_msfe   <- clean_stat_string(eval_df$DM_MSFE[i])
    dm_mafe   <- clean_stat_string(eval_df$DM_MAFE[i])
    mz_test   <- clean_stat_string(eval_df$MZ[i])
    unbias    <- clean_stat_string(eval_df$Unbias[i])
    strong    <- clean_stat_string(eval_df$Strong_Eff[i])
    weak      <- clean_stat_string(eval_df$Weak_Eff[i])
    
    row_line  <- sprintf("%d & %s & %s & %s & %s & %s & %s & %s & %s \\\\",
                         horizon, msfe_rat, dm_msfe, mafe_rat, dm_mafe, mz_test, unbias, strong, weak)
    latex_lines <- c(latex_lines, row_line)
  }
  
  # Construct the academic footnote inserting the needed information
  footnote <- sprintf(
    paste0(
      "\\hline\\hline\n",
      "\\end{tabular}%%\n",
      "%% \\\\\n",
      "\\par\\smallskip\n",
      "\\parbox{\\textwidth}{\\scriptsize \\textit{Notes:} This table reports ",
      "pseudo-out-of-sample forecast evaluation metrics for the %s against an ",
      "unconstrained %s benchmark. The evaluation period spans %s using a %s ",
      "estimation scheme with a benchmark sample start date of %s. Columns 2 and 4 ",
      "present absolute and squared forecast error ratios (values $< 1.00$ denote ",
      "model outperformance). Tests are as follows: Diebold-Mariano (DM) statistics, ",
      "Mincer-Zarnowitz (MZ) forecast optimality, Systemic over or ",
      "underprediction (Unbias), if the forecast itself predicts forecast errors (Strong),",
      "and serial correlation in forecast errors (Weak). ",
      "All $p$-values provided in parentheses}"
    ),
    model_name, benchmark, eval_period, scheme, est_start
  )
  
  latex_lines <- c(latex_lines, footnote, "\\end{table}")
  
  # Combine the character vectors into a single string block
  final_latex <- paste(latex_lines, collapse = "\n")
  
  # Output handling: Write to file or print out for Rmd
  if (!is.null(output_path)) {
    writeLines(final_latex, output_path)
    message(paste("Successfully saved LaTeX table to:", output_path))
  } else {
    cat(final_latex, "\n")
  }
  
  return(invisible(final_latex))
}

#' Generate LaTeX Table of State-Space Model Parameter Specifications
#'
#' Converts a parameter manifest list into a structured, publication-ready LaTeX
#' table detailing initial values, parameter categories, and optimization constraints
#' (fixed, unconstrained, logit, exponential, or bounded intervals).
#'
#' @param manifest_source A named list of parameter metadata objects, where each element
#'   contains \code{val} (initial values), \code{rule} (numeric optimization constraint code),
#'   optional boundary limits (\code{low}, \code{high}), and optional \code{category} labels.
#' @param model_name Character. Model label used for table captions, LaTeX labels, and console logging.
#' @param save_path Optional character string specifying the file path where the \code{.tex} table
#'   should be saved. Creates parent directories recursively if they do not exist.
#'
#' @return A character string containing the complete, compiled LaTeX table code.
#'
#' @export
generate_param_latex_table <- function(manifest_source, model_name, save_path = NULL) {
  
  # 1. Initialize LaTeX Table Header Architecture
  tex_lines <- c(
    "\\begin{table}[htbp]",
    "\\centering",
    sprintf("\\caption{%sl: Parameter Guesses and Constraints}", model_name),
    sprintf("\\label{tab:%s_ssm_specs}", tolower(gsub(" ", "_", model_name))),
    "\\begin{tabular}{llcl}",
    "\\hline\\hline",
    "\\textbf{Parameter Type} & \\textbf{Name} & \\textbf{Initial Value} & \\textbf{Restriction} \\\\ \\hline"
  )
  
  # Dynamicalli make name injections
  for (param_name in names(manifest_source)) {
    if (is.null(manifest_source[[param_name]]$category)) {
      if (grepl("^gamma|^phi|^beta|^psi", param_name)) {
        manifest_source[[param_name]]$category <- "Structural Coefficients"
      } else if (grepl("^sigma|^rho", param_name)) {
        # FIX: Escape ampersands here inside the string text for LaTeX safety
        manifest_source[[param_name]]$category <- "Measurement Innovation"
      } else if (grepl("^xi", param_name)) {
        manifest_source[[param_name]]$category <- "State Innovation"
      } else {
        manifest_source[[param_name]]$category <- "Other Parameters"
      }
    }
    manifest_source[[param_name]]$name <- param_name
  }
  
  # 2. Group the components by their category attribute
  categories <- unique(sapply(manifest_source, function(x) x$category))
  
  for (cat in categories) {
    # Add category sub-header row line
    tex_lines <- c(tex_lines, sprintf("\\textit{%s} &&& \\\\", cat))
    
    # Filter variables belonging strictly to this group
    cat_items <- manifest_source[sapply(manifest_source, function(x) x$category == cat)]
    
    for (item in cat_items) {
      # Decode optimization rules into human-readable text strings
      restriction_text <- switch(as.character(item$rule),
                                 "-1" = "Fixed",
                                 "0"  = "Unconstrained",
                                 "1"  = "Exponential ($>0$)",
                                 "2"  = "Logit ($[0, 1]$)",
                                 "3"  = sprintf("Bounded: $[%s, %s]$", 
                                                format(item$low, nsmall = 3), format(item$high, nsmall = 3)),
                                 "Unknown Mapping Setup"
      )
      
      # Parsing If item$val is a vector, collapse it cleanly
      if (length(item$val) > 1) {
        val_string <- paste0("[", paste(format(item$val, nsmall = 1), collapse = ", "), "]")
      } else {
        val_string <- format(item$val, nsmall = 2)
      }
      
      # Format individual row strings escaping the underscores safely for LaTeX compiler
      escaped_name <- gsub("_", "\\_", item$name, fixed = TRUE)
      
      row_string <- sprintf("    & \\texttt{%s} & %s & %s \\\\", 
                            escaped_name, 
                            val_string, 
                            restriction_text)
      
      tex_lines <- c(tex_lines, row_string)
    }
    # Add a horizontal line at the end of each block
    tex_lines <- c(tex_lines, "\\hline")
  }
  
  #Remove duplicate hlines,
  # we overwrite that last entry or simply append a single line here to create '\\hline\\hline'
  if (tex_lines[length(tex_lines)] == "\\hline") {
    tex_lines[length(tex_lines)] <- "\\hline\\hline"
  } else {
    tex_lines <- c(tex_lines, "\\hline\\hline")
  }
  
  tex_lines <- c(
    tex_lines, 
    "\\end{tabular}",
    "\\end{table}"
  )
  
  full_tex_code <- paste(tex_lines, collapse = "\n")
  
  # Handle Disk Export Saving Operations
  if (!is.null(save_path)) {
    dir_target <- dirname(save_path)
    if (!dir.exists(dir_target)) dir.create(dir_target, recursive = TRUE)
    
    writeLines(full_tex_code, con = save_path)
    message(sprintf("[SUCCESS] Exported %s parameter LaTeX matrix file to: %s", model_name, save_path))
  }
  
  return(full_tex_code)
}
